version: "2"

services:
  postgres:
    image: postgres:11.4
    mem_limit: 512m
    environment:
      - POSTGRES_PASSWORD=alfresco
      - POSTGRES_USER=alfresco
      - POSTGRES_DB=alfresco
    command: postgres -c max_connections=300 -c log_min_messages=LOG
    volumes:
      - ./data/postgres-keycloak:/var/lib/postgresql/data
      - ./postgres:/docker-entrypoint-initdb.d

  keycloak:
    image: jboss/keycloak:8.0.0
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: alfresco
      DB_SCHEMA: public
      DB_PASSWORD: alfresco
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    ports:
      - 8080:8080
